#!/bin/bash
# Resume Analyzer - Quick Start Deployment Script
# This script contains all the configuration you need for Render

echo "=========================================="
echo "Resume Analyzer - Deployment Checklist"
echo "=========================================="
echo ""

echo "✅ STEP 1: Code Pushed to GitHub"
echo "   Repository: https://github.com/mandalejayesh10-stack/resume-analyzer"
echo ""

echo "✅ STEP 2: Backend is Ready"
echo "   - Build Command: pip install -r backend/requirements.txt"
echo "   - Start Command: uvicorn backend.main:app --host 0.0.0.0 --port 10000"
echo ""

echo "✅ STEP 3: Environment Variables Ready"
echo "   OPENAI_API_KEY = your_openai_key (optional, leave blank if you don't have one)"
echo "   DATABASE_URL = sqlite:///./resume_analyzer.db"
echo "   REDIS_URL = redis://localhost:6379"
echo "   CORS_ORIGINS = *"
echo ""

echo "=========================================="
echo "MANUAL STEPS ON RENDER:"
echo "=========================================="
echo ""
echo "1️⃣  Go to: https://dashboard.render.com"
echo ""
echo "2️⃣  Click: 'New +' → 'Web Service'"
echo ""
echo "3️⃣  Select: 'Connect a repository'"
echo "   - Choose: resume-analyzer"
echo "   - Branch: main"
echo ""
echo "4️⃣  Fill Settings:"
echo "   Name: resume-analyzer-backend"
echo "   Environment: Python 3"
echo "   Region: Ohio"
echo "   Build Command: pip install -r backend/requirements.txt"
echo "   Start Command: uvicorn backend.main:app --host 0.0.0.0 --port 10000"
echo ""
echo "5️⃣  Click 'Advanced' → Add Environment:"
echo ""
echo "   OPENAI_API_KEY = (your key or leave blank)"
echo "   DATABASE_URL = sqlite:///./resume_analyzer.db"
echo "   REDIS_URL = redis://localhost:6379"
echo "   CORS_ORIGINS = *"
echo ""
echo "6️⃣  Click: 'Create Web Service'"
echo ""
echo "7️⃣  Wait 3-5 minutes for deployment"
echo ""
echo "8️⃣  Test: https://your-service.onrender.com/"
echo "   You should see: {\"message\": \"AI Resume Analyzer API\", \"status\": \"running\"}"
echo ""
echo "=========================================="
echo "If deployment fails:"
echo "=========================================="
echo "1. Check 'Logs' tab in Render"
echo "2. Look for error messages"
echo "3. Verify all environment variables are set"
echo "4. Try: 'Clear cache & deploy'"
echo ""
